theme: jekyll-theme-minimal
locale                   : "ko" # 타깃 국가 설정
title                    : "ok-cp" # 블로그 좌측상단의 제목
name                     : "ok-cp"
description              : "블로그 설명"
url                      : "https://ok-cp.github.io" # 블로그 주소
repository               : "ok-cp/ok-cp.github.io" # 블로그 github 리포지토리
search                   : true # 사이트 우측 상단 검색 활성화
search_full_content      : # 제목이 아닌 내용까지도 검색할 것인지에 대한 설정 기본 false
author:
  name             : "ok-cp"
  avatar           : "/assets/images/bio-photo.jpg" # 프로필 사진
  bio              : "이름 아래 나타날 자신의 설명"
  location         : "Seoul,Korea"
  email            : "bum1029@kakao.com"
  uri              : # 웹사이트, 보통 지금 블로그 말고 링크해두고 싶은 사이트를 적는다.
  # 이 아래 쇼셜 리스트에 해당되는 것에 아이디를 적는다
  github : "username" # 주소 전체를 적는 것이 아닌 자신의 정보만 적는다.
  # Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false # 해당 포스트를 읽은 시간이 표시되는데 기본값은 true이다.
      comments: # true
      share: true # 포스트 공유 기능을 활성화 할 것인지 정한다. 기본값은 true이다.
      related: true